apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pg-operator
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: pgo
      version: 5.4.1
      sourceRef:
        kind: HelmRepository
        name: crunchydata
      interval: 12h
  targetNamespace: postgres
  install:
    crds: Create
    createNamespace: true
  upgrade:
    crds: CreateReplace
