---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: secrets-store-csi-driver
spec:
  interval: 24h
  url: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: csi-secrets-store
spec:
  interval: 30m
  chart:
    spec:
      chart: secrets-store-csi-driver
      version: "1.3.3"
      sourceRef:
        kind: HelmRepository
        name: secrets-store-csi-driver
      interval: 12h
  targetNamespace: kube-system
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
