apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
spec:
  interval: 30m
  chart:
    spec:
      chart: grafana
      version: 7.x.x
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 12h
  values:
    podAnnotations:
      sidecar.istio.io/inject: "true"
    plugins: []
    grafana.ini:
      server:
        domain: monitoring.example.com # Overridden via patch
        root_url: "https://%(domain)s/"
