apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: goharbor
spec:
  values:
    expose:
      ingress:
        hosts:
          core: registry.${PRIVATE_DOMAIN}
    externalURL: https://registry.${PRIVATE_DOMAIN}
