apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dash
resources:
  - ns.yaml
  - monitoring-repo.yaml
  - monitoring-dashboards.yaml
  - postgres.yaml
  - ../../base/grafana
patchesStrategicMerge:
  - grafana-patches/release.yaml
  - grafana-patches/virtual-service.yaml
