apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: dash
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-15.4-0
  postgresVersion: 15
  users:
    - name: grafana
      databases:
        - grafana
  instances:
    - name: instance1
      dataVolumeClaimSpec:
        storageClassName: openebs-hostpath
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 20Gi
    - name: instance2
      dataVolumeClaimSpec:
        storageClassName: openebs-hostpath
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 20Gi
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.47-0
      global:
        repo1-retention-full: "7"
        repo1-retention-full-type: time
      repos:
      - name: repo1
        schedules:
          full: "0 1 * * *"
        volume:
          volumeClaimSpec:
            storageClassName: longhorn
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 20Gi