apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nextcloud
resources:
  - ns.yaml
  - postgres.yaml
  - ../../base/nextcloud
patchesStrategicMerge:
  - patches/release.yaml
  - patches/virtual-service.yaml
