kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: kindest/node:v1.26.4
  extraPortMappings:
  - containerPort: 32080
    hostPort: 80
    listenAddress: "127.0.0.1"
  - containerPort: 32443
    hostPort: 443
    listenAddress: "127.0.0.1"
