---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-system
  namespace: flux-system
spec:
  interval: 1h
  sourceRef:
    kind: GitRepository
    name: cluster
  path: ./apps/metallb-system
  prune: true
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-vars
