---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vault
  namespace: flux-system
spec:
  interval: 1h
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/hashicorp-vault
  prune: true
  patches:
    - patch: |-
        apiVersion: helm.toolkit.fluxcd.io/v2beta1
        kind: HelmRelease
        metadata:
          name: vault
          namespace: flux-system
        spec:
          values:
            global:
              externalVaultAddr: "${VAULT_ADDR}"
  postBuild:
    substituteFrom:
      - kind: Secret
        name: vault-vars
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: vault-vault-csi-provider-token
  namespace: vault
  annotations:
    kubernetes.io/service-account.name: vault-vault-csi-provider
