---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ceph-csi-cephfs
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: ceph-csi-cephfs
      version: 3.10.0
      sourceRef:
        kind: HelmRepository
        name: ceph-csi
      interval: 12h
  targetNamespace: ceph-csi
  install:
    crds: Create
    createNamespace: true
  upgrade:
    crds: CreateReplace
