apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-base
spec:
  interval: 30m
  chart:
    spec:
      chart: base
      version: 1.21.0
      sourceRef:
        kind: HelmRepository
        name: istio
      interval: 12h
  targetNamespace: istio-system
  install:
    createNamespace: true
    crds: Create
  upgrade:
    crds: CreateReplace
