---
apiVersion: v1
kind: Service
metadata:
  name: gitlab
  labels:
    app: gitlab
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  - name: ssh
    protocol: TCP
    port: 22
    targetPort: ssh
  type: ClusterIP
  selector:
    app: gitlab
