---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gitlab
spec:
  selector:
    matchLabels:
      app: gitlab
  serviceName: "gitlab"
  replicas: 1
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: gitlab
        image: gitlab/gitlab-ce:16.5.2
        envFrom:
        - configMapRef:
            name: gitlab
            optional: true
        - secretRef:
            name: gitlab-settings
            optional: true
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        - containerPort: 22
          name: ssh
        volumeMounts:
        - name: config
          mountPath: /etc/gitlab
        - name: logs
          mountPath: /var/log/gitlab
        - name: data
          mountPath: /var/opt/gitlab
        - name: dshm
          mountPath: /dev/shm
      volumes:
      - name: logs
        emptyDir:
          sizeLimit: 2Gi
      - name: dshm
        emptyDir:
          sizeLimit: 256Mi
          medium: Memory
  volumeClaimTemplates:
  - metadata:
      name: config
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 8Gi
