apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: keycloak
      version: 16.1.5
      sourceRef:
        kind: HelmRepository
        name: bitnami
      interval: 12h
  targetNamespace: keycloak
  install:
    createNamespace: true
  values:
    production: true
    proxy: edge
    postgresql:
      enabled: false
    externalDatabase:
      existingSecret: "keycloak-pguser"
      existingSecretHostKey: ""
      existingSecretPortKey: ""
      existingSecretUserKey: ""
      existingSecretDatabaseKey: ""
      existingSecretPasswordKey: ""
