---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: goharbor
spec:
  hosts: []
  gateways: []
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 80
        host: harbor
