apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: goharbor
spec:
  interval: 30m
  chart:
    spec:
      chart: harbor
      version: 1.x.x
      sourceRef:
        kind: HelmRepository
        name: goharbor
      interval: 12h
  values:
    expose:
      # We're using istio VirtualServices for ingress
      type: ClusterIP
      # We're baking the TLS certificate into the ingress controller
      tls:
        certSource: none
    externalURL: registry.${PRIVATE_DOMAIN}
    # Not defaulting to postgres operator as this is not a "critical" service,
    #   in the sense that I don't store anything critical (yet) and I'm happy
    #   to re-build anything if this is ever lost
    database:
      type: internal
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
