apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: local-ingress
  namespace: default
spec:
  selector:
    istio: system-istio-ingress
  servers:
  - hosts:
    - ${LOCAL_DOMAIN}
    port:
      number: 80
      name: http
      protocol: HTTP
