apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: renovate-bot
resources:
  - ns.yaml
#   - ../../base/renovate-bot
# configMapGenerator:
#   - name: renovate-config
#     files:
#       - config.json
#     options:
#       disableNameSuffixHash: true
# patchesStrategicMerge:
#   - patch.yaml
