apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
spec:
  interval: 30m
  chart:
    spec:
      chart: keycloak
      version: 17.3.6
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: default
      interval: 12h
  values:
    podAnnotations:
      sidecar.istio.io/inject: "true"
    production: true
    proxy: edge
    postgresql:
      enabled: false
    externalDatabase:
      existingSecret: xxxxx-pguser-keycloak
      existingSecretHostKey: host
      existingSecretPortKey: port
      existingSecretUserKey: user
      existingSecretDatabaseKey: dbname
      existingSecretPasswordKey: password
