apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-data-1
  labels:
    app: minio
    minio: data-1
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: minio
  local:
    path: /dev/minio-1/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - athena
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data-1
  labels:
    app: minio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      minio: data-1