---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ceph-csi
  namespace: flux-system
spec:
  interval: 1h
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./common/ceph-csi
  prune: true
  # dependsOn:
  #   - name: vault
  # We only have a single worker node at this point in time
  patches:
    - patch: |-
        kind: HelmRelease
        metadata:
          name: ceph-csi-rbd
        spec:
          values:
            provisioner:
              replicaCount: 1
    - patch: |-
        kind: HelmRelease
        metadata:
          name: ceph-csi-cephfs
        spec:
          values:
            provisioner:
              replicaCount: 1

