---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: istio
  namespace: flux-system
spec:
  interval: 1h
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./common/istio
  prune: true
  dependsOn:
    - name: base
  patches:
    - patch: |-
        spec:
          values:
            meshConfig:
              numTrustedProxies: 1
      target:
        kind: HelmRelease
        name: istiod
        namespace: flux-system
