---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: istio
  namespace: flux-system
spec:
  interval: 1h
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./common/istio
  prune: true
  dependsOn:
    - name: base
  patches:
    - patch: |-    
        apiVersion: helm.toolkit.fluxcd.io/v2beta1
        kind: HelmRelease
        metadata:
          name: istiod
        spec:
          values:
            meshConfig:
              defaultConfig:
                gatewayTopology:
                  numTrustedProxies: 2
