---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: keycloak
  namespace: flux-system
spec:
  interval: 1h
  dependsOn:
    - name: base
    - name: pg-operator
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/keycloak
  prune: true
