apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitlab
  labels:
    app: gitlab
spec:
  rules:
  - host: gitlab.${PRIVATE_DOMAIN}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gitlab
            port:
              name: http
  tls:
  - hosts:
      - gitlab.${PRIVATE_DOMAIN}
    secretName: gitlab-tls
