apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitlab
resources:
  - ns.yaml
  - gitlab-ingress.yaml
  - tls.yaml
  - ../../base/gitlab
patchesStrategicMerge:
  - patches/settings.yaml
