---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitlab
spec:
  commonName: "gitlab.${PRIVATE_DOMAIN}"
  dnsNames:
    - "gitlab.${PRIVATE_DOMAIN}"
  issuerRef:
    kind: ClusterIssuer
    name: cloudflare
  secretName: gitlab-tls
