apiVersion: v1
kind: Secret
metadata:
  name: renovate-env
type: Opaque
stringData:
  # Manually specifying projects to ensure clarity
  RENOVATE_AUTODISCOVER: 'false'
  RENOVATE_GIT_AUTHOR: 'Renovate Bot <bot@renovateapp.com>'
  RENOVATE_PLATFORM: 'github'
  #  Token used to push changes with, specified in a separate secret
  # RENOVATE_TOKEN: 'renovate-user-token'
