---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: vault
      version: 0.27.0
      sourceRef:
        kind: HelmRepository
        name: hashicorp
      interval: 12h
  targetNamespace: vault
  install:
    crds: Create
    createNamespace: true
  upgrade:
    crds: CreateReplace
  values:
    server:
      enabled: false
    injector:
      enabled: false
    csi:
      enabled: true
