---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vaultwarden
  namespace: istio-system
spec:
  commonName: "vault.${PUBLIC_DOMAIN}"
  dnsNames:
    - "vault.${PUBLIC_DOMAIN}"
  issuerRef:
    kind: ClusterIssuer
    name: cloudflare
  secretName: vaultwarden-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak
  namespace: istio-system
spec:
  commonName: "login.${PUBLIC_DOMAIN}"
  dnsNames:
    - "login.${PUBLIC_DOMAIN}"
  issuerRef:
    kind: ClusterIssuer
    name: cloudflare
  secretName: keycloak-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana
  namespace: istio-system
spec:
  commonName: "dash.${PUBLIC_DOMAIN}"
  dnsNames:
    - "dash.${PUBLIC_DOMAIN}"
  issuerRef:
    kind: ClusterIssuer
    name: cloudflare
  secretName: grafana-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nextcloud
  namespace: istio-system
spec:
  commonName: "files.${PUBLIC_DOMAIN}"
  dnsNames:
    - "files.${PUBLIC_DOMAIN}"
  issuerRef:
    kind: ClusterIssuer
    name: cloudflare
  secretName: nextcloud-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: registry
  namespace: traefik
spec:
  commonName: "registry.${PRIVATE_DOMAIN}"
  dnsNames:
    - "registry.${PRIVATE_DOMAIN}"
  issuerRef:
    kind: ClusterIssuer
    name: cloudflare
  secretName: registry-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitlab
  namespace: traefik
spec:
  commonName: "gitlab.${PRIVATE_DOMAIN}"
  dnsNames:
    - "gitlab.${PRIVATE_DOMAIN}"
  issuerRef:
    kind: ClusterIssuer
    name: cloudflare
  secretName: gitlab-tls
