---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: registry
spec:
  commonName: "registry.${PRIVATE_DOMAIN}"
  dnsNames:
    - "registry.${PRIVATE_DOMAIN}"
  issuerRef:
    kind: ClusterIssuer
    name: cloudflare
  secretName: registry-tls
