---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: metallb
      version: 0.13.12
      sourceRef:
        kind: HelmRepository
        name: metallb
      interval: 12h
  targetNamespace: metallb-system
  install:
    crds: Create
    createNamespace: true
  upgrade:
    crds: CreateReplace
