---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 30m
  chart:
    spec:
      chart: longhorn
      version: 1.5.3
      sourceRef:
        kind: HelmRepository
        name: longhorn
      interval: 12h
  targetNamespace: longhorn-system
  install:
    crds: Create
    createNamespace: true
  upgrade:
    crds: CreateReplace
