---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: jsonnet-controller
  namespace: flux-system
spec:
  interval: 12h
  ref:
    branch: main
  timeout: 60s
  url: https://github.com/pelotech/jsonnet-controller
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: jsonnet-controller
  namespace: flux-system
spec:
  interval: 24h
  sourceRef:
    kind: GitRepository
    name: jsonnet-controller
  path: ./config/default
  prune: true