apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
spec:
  values:
    grafana.ini:
      server:
        domain: dash.${PUBLIC_DOMAIN}
      auth:
        disable_login_form: true
        signout_redirect_url: https://login.${PUBLIC_DOMAIN}/realms/${KEYCLOAK_REALM}/protocol/openid-connect/logout?post_logout_redirect_uri=https%3A%2F%2dash.${PUBLIC_DOMAIN}%2Flogin
      auth.basic:
        enabled: false
      auth.generic_oauth:
        enabled: true
        auto_login: true
        name: ${KEYCLOAK_REALM}
        allow_sign_up: true
        client_id: $__file{/etc/secrets/auth_generic_oauth/client_id}
        client_secret: $__file{/etc/secrets/auth_generic_oauth/client_secret}
        scopes: openid email profile offline_access
        email_attribute_path: email
        login_attribute_path: username
        name_attribute_path: full_name
        auth_url: https://login.${PUBLIC_DOMAIN}/realms/${KEYCLOAK_REALM}/protocol/openid-connect/auth
        token_url: https://login.${PUBLIC_DOMAIN}/realms/${KEYCLOAK_REALM}/protocol/openid-connect/token
        api_url: https://login.${PUBLIC_DOMAIN}/realms/${KEYCLOAK_REALM}/protocol/openid-connect/userinfo
        allow_assign_grafana_admin: true
        role_attribute_path: contains(roles[*], 'grafanaadmin') && 'GrafanaAdmin' || contains(roles[*], 'admin') && 'Admin' || contains(roles[*], 'editor') && 'Editor' || 'Viewer'
      database:
        type: postgres
        host: $__file{/etc/secrets/postgres/host}:$__file{/etc/secrets/postgres/port}
        name: $__file{/etc/secrets/postgres/dbname}
        user: $__file{/etc/secrets/postgres/user}
        password: $__file{/etc/secrets/postgres/password}
        ssl_mode: verify-ca
        client_key_path: /etc/secrets/postgres-certs/tls.key
        client_cert_path: /etc/secrets/postgres-certs/tls.crt
        ca_cert_path: /etc/secrets/postgres-certs/ca.crt
    extraSecretMounts:
      - name: postgres-secrets-mount
        secretName: dash-pguser-grafana
        defaultMode: 0440
        mountPath: /etc/secrets/postgres
        readOnly: true
      - name: postgres-certs-mount
        secretName: dash-cluster-cert
        defaultMode: 0440
        mountPath: /etc/secrets/postgres-certs
        readOnly: true
      - name: auth-generic-oauth-secrets-mount
        secretName: grafana-oauth
        defaultMode: 0440
        mountPath: /etc/secrets/auth_generic_oauth
        readOnly: true
