apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph
spec:
  interval: 30m
  chart:
    spec:
      chart: rook-ceph
      version: 1.13.1
      sourceRef:
        kind: HelmRepository
        name: rook-release
      interval: 12h
  targetNamespace: rook-ceph
  install:
    createNamespace: true
    crds: Create
  upgrade:
    crds: CreateReplace
