apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
spec:
  interval: 30m
  chart:
    spec:
      chart: grafana
      version: 7.0.11
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 12h
  values:
    podAnnotations:
      sidecar.istio.io/inject: "true"
    plugins: []
    grafana.ini:
      server:
        domain: monitoring.example.com # Overridden via patch
        root_url: "https://%(domain)s/"
    sidecar:
      dashboards:
        enabled: true
        label: grafana_dashboard
        labelValue: "1"
        folder: /tmp/dashboards
        folderAnnotation: grafana_folder
        provider:
          foldersFromFilesStructure: true
    dashboardProviders:
      monitoring-provider.yaml:
        apiVersion: 1
        providers:
          - name: 'kubernetes'
            orgId: 1
            folder: 'kubernetes'
            type: file
            disableDeletion: false
            editable: false
            options:
              path: /tmp/dashboards/kubernetes
          - name: 'flux'
            orgId: 1
            folder: 'flux'
            type: file
            disableDeletion: false
            editable: false
            options:
              path: /tmp/dashboards/flux
