---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/local
  prune: true
  postBuild:
    substituteFrom:
      - kind: Secret
        name: app-vars
  dependsOn:
    - name: base
    - name: monitoring
