---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: helm-repos
  namespace: default
spec:
  interval: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./common/helm-repos
  prune: true
