---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring
  namespace: flux-system
spec:
  interval: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./common/monitoring
  prune: true
  dependsOn:
    - name: base
  postBuild:
    substituteFrom:
      - kind: Secret
        name: app-vars
  patches:
    - patch: |-
        apiVersion: helm.toolkit.fluxcd.io/v2beta1
        kind: HelmRelease
        metadata:
          name: prometheus-stack
        spec:
          chart:
            spec:
              chart: kube-prometheus-stack
          targetNamespace: monitoring
          values:
            grafana:
              enabled: true
              grafana.ini:
                server:
                  domain: ${LOCAL_DOMAIN}
                  root_url: "http://${LOCAL_DOMAIN}/grafana/"
                  serve_from_sub_path: "true"
              ingress:
                enabled: true
                hosts:
                - ${LOCAL_DOMAIN}
                path: /grafana
              additionalDatasources:
              - name: Loki
                type: loki
                isDefault: false
                access: proxy
                url: http://{{ .Release.Namespace }}-loki-stack:3100
                version: 1
