---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 24h
  url: https://traefik.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: traefik
      version: "25.x"
      sourceRef:
        kind: HelmRepository
        name: traefik
      interval: 12h
  targetNamespace: traefik
  install:
    crds: Create
    createNamespace: true
  upgrade:
    crds: CreateReplace
  values:
    hostNetwork: true
    logs:
      access:
        enabled: true
