---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./common/traefik
  prune: true
  dependsOn:
    - name: base
    - name: monitoring
  patches:
    - patch: |-
        apiVersion: helm.toolkit.fluxcd.io/v2beta1
        kind: HelmRelease
        metadata:
          name: traefik
          namespace: flux-system
        spec:
          values:
            ports:
              web:
                nodePort: 32080
              websecure:
                nodePort: 32443
