apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vaultwarden
  name: vaultwarden
spec:
  template:
    spec:
      containers:
      - name: vaultwarden
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: auth-pguser-vaultwarden
              key: uri
