---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 1h
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./common/cilium
  prune: true
  patches:
    - patch: |-
        apiVersion: helm.toolkit.fluxcd.io/v2beta1
        kind: HelmRelease
        metadata:
          name: cilium
          namespace: kube-system
        spec:
          values:
            cni:
              confPath: /var/snap/microk8s/current/args/cni-network
              binPath: /var/snap/microk8s/current/opt/cni/bin
